version: "3.9"
services:
  postgrest:
    image: postgrest/postgrest:v10.1.2
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: "postgres://postgres:postgres@postgres:5432/postgres"
      PGRST_OPENAPI_SERVER_PROXY_URI: "http://127.0.0.1:3000"
      PGRST_DB_ANON_ROLE: "web_anon"
      PGRST_DB_MAX_ROWS: "50"
    depends_on:
      - postgres
  postgres:
    image: postgis/postgis:14-3.2
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
        ]
      interval: "10s"
      timeout: "5s"
      retries: 5
  generator:
    # platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.generator
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      GITHUB_WORKSPACE: /usr/app
      TILESET_NAME: trees.mbtiles
      GITHUB_TOKEN: "123"
    entrypoint: [ "tail", "-f", "/dev/null" ]
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./_data/tilesets:/tilesets
      - ./:/usr/app
      - ./_data/temp:/tmp
