version: "3.9"
services:
    mbtileserver:
        environment:
            # these variables are used in the entrypoint.sh script
            - TILESET_DIR=/tilesets
            - TMP_DIR=/tmp
            - GITHUB_TOKEN=${GITHUB_TOKEN}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
            - AWS_BUCKET=${AWS_BUCKET}
            - TILESET_NAME=${TILESET_NAME}
            # The values below need to be changed in production
            # - POSTGRES_HOST=postgres
            # - POSTGRES_DB=postgres
            # - POSTGRES_USER=postgres
            # - POSTGRES_PASSWORD=postgres
            # or you use an .env file for this
            # env_file:
            #     - .env
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - BASE_IMAGE=qtrees-vectortiles-generator-base:test
        container_name: qtrees-vectortiles-generator
        # in production this should have the following command
        command: --dir /tilesets --enable-fs-watch
        restart: always
        ports:
            - 26080:8000
        volumes:
            - tilesets:/tilesets
volumes:
    tilesets:
