# NOTE: This file is just an example os is not used in our current setup
# We set the render service manually because we use two environments.
# Staging and production.
services:
  - type: web
    name: qtrees-vectortiles
    env: docker
    plan: starter
    region: frankfurt
    autoDeploy: false
    dockerContext: .
    dockerfilePath: Dockerfile.server
    envVars:
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_DEFAULT_REGION
        sync: false
      - key: AWS_BUCKET
        sync: false

      - key: BASE_IMAGE
        value: technologiestiftung/qtrees-vectortiles_base:2.6.2
        sync: true
      - key: TILESET_NAME
        value: trees.mbtiles
        sync: true
      - key: TILESET_DIR
        value: /tilesets
        sync: true
      - key: TMP_DIR
        value: /tmp
        sync: true
