services:
  - type: web
    name: qtrees-vectortiles
    env: docker
    plan: starter
    region: frankfurt
    autoDeploy: false
    dockerContext: .
    dockerfilePath: Dockerfile.render
    envVars:
      - key: POSTGRES_HOST
        generateValue: false
      - key: POSTGRES_DB
        generateValue: false
      - key: POSTGRES_USER
        generateValue: false
      - key: POSTGRES_PASSWORD
        generateValue: false
