name: Debug generator
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TILESET_NAME: trees.mbtiles
  TILESET_DIR: /tilesets
  TMP_DIR: /tmp
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_BUCKET: ${{ secrets.AWS_TEST_BUCKET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

on:
  push:
    branches: ['test/QTREES-439/add-tests-for-vectortiles-generator-script']
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
  release:
    types: [published]

jobs:
  test-generator:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-20.04
    container:
      image: technologiestiftung/qtrees-vectortiles-generator-base:2.5
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout technologiestiftung/qtrees-vectortiles-generator
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - run: npm ci

      - run: node __tests__/init-generator-test.js
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_HOST: postgres
      - name: test docker compose
        env:
          # bump
          POSTGRES_HOST: postgres
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: '5432'

          TILESET_DIR: /tilesets
          TILESET_NAME: trees.mbtiles
          TMP_DIR: /tmp
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
          AWS_BUCKET: ${{ secrets.AWS_TEST_BUCKET }}

        run: |
          echo "Running the generator"
          ./generator.sh
      - name: Tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 10
        with:
          limit-access-to-actor: true
