name: Tileset Generator
on:
    repository_dispatch:
        types: [nightly-release]
    workflow_dispatch: {}

jobs:
    generator:
        name: A job to generate the tileset
        runs-on: ubuntu-latest
        container:
            image: technologiestiftung/qtrees-vectortiles-generator-base:2.2.0
            credentials:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            env:
                POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
                POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
                POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
                POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
                POSTGRES_PORT: '5432'
                TILESET_DIR: /tilesets
                TILESET_NAME: trees.mbtiles
                TMP_DIR: /tmp
            # volumes:
            #     - /tilesets:/tilesets
        steps:
            - name: Create tilesetdir
              run: mkdir -p $TILESET_DIR
            - name: Checkout source repository
              uses: actions/checkout@v3
            - name: Run the generator
              id: generator
              run: |
                  echo "Running the generator"
                  ./generator.sh

            - name: Output path
              run: |
                  echo "The path of the generated tileset is ${{ steps.generator.outputs.tileset_path }}"
            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: tileset
                  path: trees.mbtiles
                  if-no-files-found: error
              # add tmate action to debug
            # - name: Setup tmate session
            #   if: ${{ failure() }}
            #   uses: mxschmitt/action-tmate@v3
            #   # if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
            #   timeout-minutes: 3
            #   with:
            #       limit-access-to-actor: true
            #   # now notify the render to use the new tileset
            #   # by downloading it and restarting the server
